server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zeinaabdallah/soms-config
          default-label: main
          clone-on-start: true
          # For a private repo, set these as env vars:
          # username: ${GIT_USERNAME}
          # password: ${GIT_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
